services:
  # Frontend service (React)
  frontend:
    build:
      context: ./log_analyzer  # Frontend build context
    ports:
      - "80:80"  # Expose port 80 for frontend access
    depends_on:
      - backend  # Ensure the backend is running before the frontend

  # Database service (MySQL)
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}  # Use password from .env file
      MYSQL_DATABASE: ${MYSQL_DATABASE}
        # Use database name from .env file
    ports:
      - "3306:3306"  # Expose MySQL port 3306
    volumes:
      - mariadb_data:/var/lib/mysql  # Persist MySQL data between container restarts
    env_file:
      - .env  # Load environment variables from .env file

  backend:
    build:
      context: ./log_validation_backend 
    environment:
      - DB_HOST=db  
      - DJANGO_AUTO_MIGRATE=1
    command: >
      sh -c "
      /wait-for-db.sh &&
      if [ $$DJANGO_AUTO_MIGRATE -eq 1 ]; then
        python manage.py migrate;
      fi &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"  
    env_file:
      - .env  
    depends_on:
      - db  

volumes:
  mariadb_data: 
