
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: 'log-analyzer'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./log_validation_backend
    container_name: django_app
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn log_validation_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./log_validation_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    environment:
      - DB_NAME=log-analyzer
      - DB_USER=root
      - DB_PASSWORD=
      - DB_HOST=mysql_db    

  frontend:
    build:
      context: ./log_analyzer
    container_name: react_app
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./log_analyzer:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - django_app
      - react_app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mysql_data:
  
