services:
  Localhost:
    build:
      context: ./log_validation_backend
      dockerfile: Dockerfile
    container_name: django-backend
    env_file:
      - ./log_validation_backend/log_validation_backend/.env
    volumes:
      - ./log_validation_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./log_analyzer
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - ./log_analyzer:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: log-analyzer
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
