# Generated by Django 5.2 on 2025-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConduitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=150, null=True)),
                ('nbrfile', models.FloatField()),
                ('code', models.CharField(max_length=50, null=True)),
                ('type_gega', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=30, null=True)),
                ('frequence', models.IntegerField(null=True)),
                ('delta', models.IntegerField(null=True)),
                ('ant', models.IntegerField(null=True)),
                ('evm', models.FloatField(null=True)),
                ('power_rms_avg', models.FloatField(null=True)),
                ('power_rms_max', models.FloatField(null=True)),
                ('power_rms_min', models.FloatField(null=True)),
                ('power_dbm_rms_avg', models.FloatField(null=True)),
                ('power_dbm_rms_max', models.FloatField(null=True)),
                ('power_dbm_rms_min', models.FloatField(null=True)),
                ('power_peak_avg', models.FloatField(null=True)),
                ('power_peak_max', models.FloatField(null=True)),
                ('power_peak_min', models.FloatField(null=True)),
                ('power_pre_avg', models.FloatField(null=True)),
                ('power_pre_max', models.FloatField(null=True)),
                ('power_pre_min', models.FloatField(null=True)),
                ('error_message', models.TextField(null=True)),
                ('test_time', models.FloatField(null=True)),
                ('limit_min', models.FloatField(null=True)),
                ('limit_max', models.FloatField(null=True)),
                ('rssi', models.FloatField(null=True)),
                ('rssi_min', models.FloatField(null=True)),
                ('rssi_max', models.FloatField(null=True)),
                ('evm_min', models.FloatField(null=True)),
                ('evm_max', models.FloatField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['delta'], name='conduit_delta_idx'), models.Index(fields=['description'], name='conduit_desc_idx'), models.Index(fields=['rssi'], name='conduit_rssi_idx'), models.Index(fields=['power_rms_avg'], name='conduit_power_idx'), models.Index(fields=['evm'], name='conduit_evm_idx'), models.Index(fields=['delta', 'description'], name='conduit_delta_desc_idx')],
            },
        ),
    ]
