# Generated by Django 5.2 on 2025-05-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_conduit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conduitresult',
            name='freq_error_avg_max',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='freq_error_avg_min',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='lo_leakage_dbc_limit',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='lo_leakage_margin_min',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='margin_db_lo_a_min',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='margin_db_lo_b_min',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='margin_db_up_a_min',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='margin_db_up_b_min',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='obw_mhz_max',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='obw_mhz_min',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='violation_percentage_max',
        ),
        migrations.RemoveField(
            model_name='conduitresult',
            name='violation_percentage_min',
        ),
    ]
