# Generated by Django 5.2 on 2025-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_conduit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduitresult',
            name='ressource',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
