# Generated by Django 5.2 on 2025-04-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_conduit', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conduitresult',
            index=models.Index(fields=['delta'], name='conduit_delta_idx'),
        ),
        migrations.AddIndex(
            model_name='conduitresult',
            index=models.Index(fields=['description'], name='conduit_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='conduitresult',
            index=models.Index(fields=['rssi'], name='conduit_rssi_idx'),
        ),
        migrations.AddIndex(
            model_name='conduitresult',
            index=models.Index(fields=['power_rms_avg'], name='conduit_power_idx'),
        ),
        migrations.AddIndex(
            model_name='conduitresult',
            index=models.Index(fields=['evm'], name='conduit_evm_idx'),
        ),
        migrations.AddIndex(
            model_name='conduitresult',
            index=models.Index(fields=['delta', 'description'], name='conduit_delta_desc_idx'),
        ),
    ]
