# Generated by Django 5.1.6 on 2025-05-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_conduit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conduitresult',
            name='freq_error_avg',
        ),
    ]
