# Generated by Django 5.1.6 on 2025-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_conduit', '0002_remove_conduitresult_freq_error_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduitresult',
            name='freq_error_avg',
            field=models.FloatField(null=True),
        ),
    ]
