# Generated by Django 5.1.6 on 2025-05-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_conduit', '0005_remove_conduitresult_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conduitresult',
            name='conduit_delta_idx',
        ),
        migrations.RemoveIndex(
            model_name='conduitresult',
            name='conduit_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='conduitresult',
            name='conduit_rssi_idx',
        ),
        migrations.RemoveIndex(
            model_name='conduitresult',
            name='conduit_power_idx',
        ),
        migrations.RemoveIndex(
            model_name='conduitresult',
            name='conduit_evm_idx',
        ),
        migrations.RenameField(
            model_name='conduitresult',
            old_name='type_gega',
            new_name='bande',
        ),
    ]
