# Generated by Django 5.2 on 2025-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NftResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure', models.CharField(max_length=50, null=True)),
                ('bande', models.CharField(max_length=10, null=True)),
                ('antenne', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('lim_min', models.IntegerField(blank=True, null=True)),
                ('lim_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
