# Generated by Django 5.1.6 on 2025-05-22 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NftResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('lim_min', models.FloatField(blank=True, null=True)),
                ('lim_max', models.FloatField(blank=True, null=True)),
                ('bande', models.CharField(blank=True, max_length=10, null=True)),
                ('antenne', models.IntegerField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=100, null=True)),
                ('unite', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wifi_nft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
