# Generated by Django 5.2 on 2025-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NftResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('lim_min', models.FloatField(blank=True, null=True)),
                ('lim_max', models.FloatField(blank=True, null=True)),
                ('bande', models.CharField(blank=True, max_length=10, null=True)),
                ('antenne', models.IntegerField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=100, null=True)),
                ('unite', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mesure'], name='wifi_nft_nf_mesure_7939fe_idx'), models.Index(fields=['bande'], name='wifi_nft_nf_bande_e1065c_idx'), models.Index(fields=['antenne'], name='wifi_nft_nf_antenne_9432c9_idx')],
            },
        ),
    ]
