# Generated by Django 5.1.6 on 2025-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftresults',
            name='power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
