# Generated by Django 5.2 on 2025-04-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0002_alter_nftresults_lim_max_alter_nftresults_lim_min_and_more'),
        ('wifi_nft', '0002_alter_nftresults_power'),
    ]

    operations = [
    ]
