# Generated by Django 5.1.6 on 2025-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0002_alter_nftresults_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftresults',
            name='source_file',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='nftresults',
            index=models.Index(fields=['power'], name='wifi_nft_nf_power_33c126_idx'),
        ),
    ]
