# Generated by Django 5.1.6 on 2025-05-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0002_nftresults_created_by'),
        ('wifi_nft', '0002_nftresults_user'),
    ]

    operations = [
    ]
