# Generated by Django 5.2 on 2025-04-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0003_merge_20250415_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftresults',
            name='lim_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nftresults',
            name='lim_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='nftresults',
            index=models.Index(fields=['power'], name='wifi_nft_nf_power_33c126_idx'),
        ),
    ]
