# Generated by Django 5.1.6 on 2025-05-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0003_merge_0002_nftresults_created_by_0002_nftresults_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftresults',
            name='User',
        ),
    ]
