# Generated by Django 5.2 on 2025-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0004_alter_nftresults_lim_max_alter_nftresults_lim_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftresults',
            name='source_file',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
