# Generated by Django 5.1.6 on 2025-05-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0004_remove_nftresults_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nftresults',
            name='wifi_nft_nf_mesure_7939fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='nftresults',
            name='wifi_nft_nf_bande_e1065c_idx',
        ),
        migrations.RemoveIndex(
            model_name='nftresults',
            name='wifi_nft_nf_antenne_9432c9_idx',
        ),
    ]
