# Generated by Django 5.1.6 on 2025-04-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0005_nftresults_source_file'),
    ]

    operations = [
    ]
