# Generated by Django 5.2 on 2025-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_nft', '0006_merge_20250416_1445'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nftresults',
            name='wifi_nft_nf_power_33c126_idx',
        ),
        migrations.RenameField(
            model_name='nftresults',
            old_name='power',
            new_name='valeur',
        ),
        migrations.AddField(
            model_name='nftresults',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nftresults',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nftresults',
            name='unite',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nftresults',
            name='bande',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nftresults',
            name='lim_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nftresults',
            name='lim_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nftresults',
            name='mesure',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nftresults',
            name='source_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='nftresults',
            index=models.Index(fields=['mesure'], name='wifi_nft_nf_mesure_7939fe_idx'),
        ),
        migrations.AddIndex(
            model_name='nftresults',
            index=models.Index(fields=['bande'], name='wifi_nft_nf_bande_e1065c_idx'),
        ),
        migrations.AddIndex(
            model_name='nftresults',
            index=models.Index(fields=['antenne'], name='wifi_nft_nf_antenne_9432c9_idx'),
        ),
    ]
