# Generated by Django 5.1.6 on 2025-05-22 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APPLICATION_VERSION', models.CharField(max_length=100, null=True)),
                ('IQFACT', models.CharField(max_length=100, null=True)),
                ('BOOTFS1', models.CharField(max_length=100, null=True)),
                ('MCU_FIRMWARE', models.CharField(max_length=100, null=True)),
                ('SROM', models.CharField(max_length=100, null=True)),
                ('IQMEASURE_VERSION', models.CharField(max_length=100, null=True)),
                ('IQTESTER_HW_VERSION_01', models.CharField(max_length=100, null=True)),
                ('Tester_1_SN', models.CharField(max_length=100, null=True)),
                ('Firmware_revision', models.CharField(max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_conditions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
