# Generated by Django 5.1.6 on 2025-05-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environnement_test', '0002_testcondition_created_by'),
        ('environnement_test', '0002_testcondition_user'),
    ]

    operations = [
    ]
