# Generated by Django 5.1.6 on 2025-05-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environnement_test', '0003_merge_20250505_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcondition',
            name='User',
        ),
    ]
