# Generated by Django 5.2 on 2025-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField()),
                ('nom', models.CharField(max_length=300)),
                ('mesure', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=10, null=True)),
                ('source_file', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mesure'], name='temps_test__mesure_69d8db_idx')],
            },
        ),
    ]
