# Generated by Django 5.2 on 2025-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempstest',
            name='heure',
            field=models.IntegerField(null=True),
        ),
    ]
