# Generated by Django 5.2 on 2025-04-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps_test', '0002_tempstest_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstest',
            name='heure',
            field=models.TimeField(null=True),
        ),
    ]
