# Generated by Django 5.2 on 2025-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps_test', '0003_alter_tempstest_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempstest',
            name='heure',
            field=models.IntegerField(null=True),
        ),
    ]
