# Generated by Django 5.1.6 on 2025-05-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temps_test', '0005_tempstest_created_by'),
        ('temps_test', '0005_tempstest_user'),
    ]

    operations = [
    ]
