# Generated by Django 5.1.6 on 2025-05-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temps_test', '0006_merge_0005_tempstest_created_by_0005_tempstest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempstest',
            name='User',
        ),
    ]
