# Generated by Django 5.1.6 on 2025-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps_test', '0007_remove_tempstest_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tempstest',
            name='temps_test__mesure_69d8db_idx',
        ),
        migrations.AddField(
            model_name='tempstest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
