"""
Django settings for log_validation_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os

from datetime import timedelta



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--*t9di6!xhf8z54cpw5+^n*!p!orxbf2%=sm&9vk%!khlig9!k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'wifi_conduit',
    'wifi_nft',
    'environnement_test',
    'temps_test',
    'auth_app',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'matricule',
    'USER_ID_CLAIM': 'matricule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    
    'TOKEN_OBTAIN_SERIALIZER': 'auth_app.serializers.MyTokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'auth_app.serializers.CookieTokenRefreshSerializer',
}


JWT_COOKIE_SETTINGS = {
    'ACCESS_TOKEN_COOKIE_NAME': 'access_token',
    'REFRESH_TOKEN_COOKIE_NAME': 'refresh_token',
    'ACCESS_TOKEN_COOKIE_PATH': '/',
    'REFRESH_TOKEN_COOKIE_PATH': '/',
    'COOKIE_SECURE': not DEBUG,  # True en production (HTTPS)
    'COOKIE_HTTPONLY': True,
    'COOKIE_SAMESITE': 'Lax',  # ou 'Strict' pour plus de sécurité
    'ACCESS_TOKEN_COOKIE_MAX_AGE': 60 * 15,  # 15 minutes
    'REFRESH_TOKEN_COOKIE_MAX_AGE': 60 * 60 * 24 * 7,  # 7 jours
}


SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Doit être False pour permettre l'accès via JS si nécessaire
CSRF_COOKIE_SAMESITE = 'Lax'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auth_app.middleware.JWTCookieMiddleware',

]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'log_validation_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'log_validation_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'log-analyzer',      # Nom de votre base de données
        'USER': 'root',              # Utilisateur par défaut de XAMPP
        'PASSWORD': '',              # Mot de passe vide pour XAMPP
        'HOST': 'Localhost',         # XAMPP tourne en local
        'PORT': '3306',              # Port par défaut de MySQL dans XAMPP
        'OPTIONS': {
            'charset': 'utf8mb4',    # Support des emojis/unicode
            'sql_mode': 'STRICT_TRANS_TABLES',  # Mode strict pour éviter les erreurs silencieuses
            'init_command': "SET foreign_key_checks = 0;",  # Désactive temporairement les vérifications de clés étrangères
        },
    }
}

AUTH_USER_MODEL = 'auth_app.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

ALLOWED_HOSTS = ['*']
CORS_ALLOW_ALL_ORIGINS = True  # For development only


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB

FILE_UPLOAD_MAX_MEMORY_SIZE = 1073741824  # 1GB

DATA_UPLOAD_MAX_NUMBER_FILES = None
